apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-app-role
  namespace: secure-app
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-app-rolebinding
  namespace: secure-app
subjects:
  - kind: ServiceAccount
    name: secure-app-sa
    namespace: secure-app
roleRef:
  kind: Role
  name: secure-app-role
  apiGroup: rbac.authorization.k8s.io